/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Datas: typeof import('./src/components/overview/datas.vue')['default']
    Gather: typeof import('./src/components/overview/gather.vue')['default']
    HeadBar: typeof import('./src/components/bar/HeadBar.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconMenu: typeof import('@yike-design/ui/es/components/svg-icon')['IconMenu']
    IconPlusOutline: typeof import('@yike-design/ui/es/components/svg-icon')['IconPlusOutline']
    IndexViews: typeof import('./src/components/bar/indexViews.vue')['default']
    Line: typeof import('./src/components/echarts/line.vue')['default']
    Menu: typeof import('./src/components/bar/Menu.vue')['default']
    Pie: typeof import('./src/components/echarts/pie.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScreenBar: typeof import('./src/components/bar/screenBar.vue')['default']
    TopTitle: typeof import('./src/components/bar/topTitle.vue')['default']
    YkBadge: typeof import('@yike-design/ui/es')['YkBadge']
    YkButton: typeof import('@yike-design/ui/es')['YkButton']
    YkSpace: typeof import('@yike-design/ui/es')['YkSpace']
    YkText: typeof import('@yike-design/ui/es')['YkText']
    YkTheme: typeof import('@yike-design/ui/es')['YkTheme']
    YkTitle: typeof import('@yike-design/ui/es')['YkTitle']
  }
}
